version: '3.8'
services:
  pyapp:
    build:
      context: ./py/
      dockerfile: Dockerfile
    ports:
      - '8729:8729'
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: 'dbservice'
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
